- name: get token for nodes
  slurp:
    src: /var/lib/rancher/k3s/server/token
  register: k3s_token
  delegate_to: "{{ groups['masters'][0] }}"
  run_once: yes

- name: install k3s on workers
  shell: "curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION={{ k3s_version }} K3S_URL=\"https://{{ k3s_master_lb_dns_name }}:6443\" K3S_TOKEN=\"{{ k3s_token['content'] | b64decode | trim }}\" sh -"
